name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v2.1.0
        id: snake-gif
        with:
          github_user_name: jefethepug
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
          
      - name: Create output directory
        run: mkdir -p dist
        
      - name: Check for changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Update snake GIF"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
    
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
